version: "3.5"
services:
  postgres:
    image: postgres:13.1
    container_name: mypostgresdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - dbnet
  adminer:
    image: adminer:4.7
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dbnet
networks:
  dbnet:
    name: dbnet
