kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage
  labels:
    app: notification
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
