apiVersion: v1
kind: Service
metadata:
  name: notification-api
  labels:
    name: notification-api
    app: notification
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    component: notification-api
